# Generated by Django 4.2.7 on 2023-12-26 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logmodel',
            options={'ordering': ('id',), 'verbose_name': 'Log', 'verbose_name_plural': 'Logs'},
        ),
        migrations.RemoveField(
            model_name='logmodel',
            name='core_method',
        ),
        migrations.RemoveField(
            model_name='logmodel',
            name='core_request_body',
        ),
        migrations.RemoveField(
            model_name='logmodel',
            name='core_request_headers',
        ),
        migrations.RemoveField(
            model_name='logmodel',
            name='proxy_response_body',
        ),
        migrations.RemoveField(
            model_name='logmodel',
            name='proxy_response_headers',
        ),
        migrations.RemoveField(
            model_name='logmodel',
            name='proxy_response_status_code',
        ),
        migrations.AlterField(
            model_name='logmodel',
            name='core_response_body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='logmodel',
            name='proxy_request_body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
