# Generated by Django 4.2.7 on 2023-12-27 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0002_alter_logmodel_options_remove_logmodel_core_method_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logmodel',
            old_name='proxy_method',
            new_name='client_request_method',
        ),
        migrations.RenameField(
            model_name='logmodel',
            old_name='core_url',
            new_name='client_request_url',
        ),
        migrations.RenameField(
            model_name='logmodel',
            old_name='proxy_url',
            new_name='proxy_request_url',
        ),
        migrations.AddField(
            model_name='logmodel',
            name='client_request_body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logmodel',
            name='client_request_headers',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logmodel',
            name='proxy_request_method',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='logmodel',
            name='proxy_response_body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logmodel',
            name='proxy_response_headers',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logmodel',
            name='proxy_response_status_code',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
